### ISSUE TITLE
LEDs not working

### ISSUE THREAD

**Issue by dfunkt** [ah-/anne-key#40]
At least for me LEDs are not working since this release: https://github.com/ah-/anne-key/releases/tag/2018-03-10-127-master-f4fe08f

**Comment by ah-** [comment]
Thanks! It should work if you manually toggle the LED chip off/on via the FN2 layer (https://github.com/ah-/anne-key/blob/master/src/layout.rs#L52). Hold the ANNE key down, then press escape, wait a second, then press 1. Afterwards the normal fn-rtyu keys should work.

This is due to us not yet having proper power management for the LED chip, I'll see if I can put something in to make it somewhat work again short-term..

**Comment by dfunkt** [comment]
For whatever reason I still can't get them to work, even after following your instructions. Wish I had something to debug the keyboard with.

**Comment by ah-** [comment]
Hmm, I'm just seeing the similar issues. Sometimes it works after a reset, sometimes it doesn't. Will investigate.

**Comment by ah-** [comment]
Can you try the lateest build once it's done? This makes it work somewhat reliably for me now. The manual toggle from earlier didn't work I think because I had local changes.

**Comment by dfunkt** [comment]
Can confirm this issue is fixed now.
